language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://rodolfouriel.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "PzXBr79HkRG/leJFu9mv/UIK/2QIrjFsu7Qxo6w0VOcMct7lk8MX7RlZW17bouTVubwN29epoPZm3a5peutuc/WTHRsbBJiDql0ulGhNhMunJH3gbRlaYFQ/rFYR6MyjgDs0rEZ8jalUgdVcZ+hdIwUdhDOUhEiPgipx+zU0YDtr7NQ9frOJEwIqGnRluq+0+siTiKQ94Lve86VM9QwrymomLHx1gRaeTrCFkHinaR3QNQrsfd9fD+RxiTolYOso5iYWDpMq/2WXeRdvMytiH4hnqa5mR1Df73Oms4wV99APoTwhwafSv9vmOX14JghFv0f2yzbSYuNcbfjffpxPJuTbt+nzUj4o6ghXJ8eXWd76/qOQSBtXaOTtrMlyeOPa6msENN9/Cl7ccfb8a7qutWc+6IwHtjrpaiGshFbQ4U3xAHXH+OswfVBfh52W6lyLluLR4smDw4UXDitEyktmTwk2OxP2bptnVI4zavcaJyAjxX0Jx2KzAuiVonOcNZeTyFhcn3cVjfFxOW4QHp5XU9e6OykZ7f1lapOFYyeqIfXIxO+30GpV1pjJAsLEjE8HuJjsNGZWDd/nBEaUBSbJRq7s+TnWEBTvTUwgNpVbYz92oHQXgKGAYQIE3bcQ6/rr0j8dcwgoCw71gfQ7+hy7kh9abEsKTMgvEF7N1YlkoMs="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
